services:
  postgres:
    image: postgres:17.4
    container_name: testnest
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: testnest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: